---
name: Deploy to Staging
on:
  push:
    branches:
      - production
jobs:
  redeploy_all:
    runs-on: ubuntu-latest
    name: Deploying everything to the servers to staging
    steps:
      - name: Deploy on Production Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 165.22.221.42
          username: root
          key: ${{ secrets.SSH_PrivateKey }}
          script: |
            cd /root/devops-cicd
            git pull origin production
            source /root/.nvm/nvm.sh
            nvm use 22
            npm i -g pnpm
            pnpm install
            pnpm run build
            pm2 restart web
            pm2 restart http-server
            pm2 restart ws-server

          
 