---
name: Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_all:
    runs-on: ubuntu-latest
    name: Deploying everything to the servers to staging
    steps:
      - name: SSH Into Server
        run: |
          echo "${{ secrets.SSH_PrivateKey }}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key root@64.227.190.16
          cd devops-cicd/ && git pull
          pnpm install
          pnpm run build
          pm2 restart web
          pm2 restart http-server
          pm2 restart ws-server
