---
name: Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_all:
    runs-on: ubuntu-latest
    name: Deploying everything to the servers to staging
    steps:
      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 64.227.190.16
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/devops-cicd
            git pull
            source /root/.nvm/nvm.sh
            nvm use 22
            npm i -g pnpm
            pnpm install
            pnpm run build
            pm2 restart web
            pm2 restart http-server
            pm2 restart ws-server

          
 