---
name: Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_all:
    name: Deploying everything to the servers to staging
    steps:
      - name: SSH Into Server
      - run: |
          echo {{ secrets.SSH_PrivateKey }} &> ~/ssh_key
          ssh -i ~/ssh_key root@64.227.190.16
          cd devops-cicd/ && git pull
          pnpm install
          pnpm run build
          pm2 restart web
          pm2 restart http-server
          pm2 restart ws-server
